version: "3.8"
services:
  mongodb:
    image: 'mongo'
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    env_file:
      - ./backend/dockerenv.env
    ports:
      - '5000:5000'
    depends_on:
      - mongodb

  frontend:
    build: ./frontend
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true 
    depends_on:
      - backend

volumes:
  mongo_data:

